package com.demo.teams;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class TeamsApplicationTests {
    @Test
    void test() {
        // Don't need tests. This is an autogenerated file.
    }
}
